name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          readme_path: "profile/README.md"
          channel_id: UCA2tFk2NdzOzKpSJdf24cAg
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          comment_tag_name: YOUTUBE-CARDS
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
